name = "LabelledGraphs"
uuid = "605abd48-4d17-4660-b914-d4df33194460"
authors = ["Konrad Jałowiecki <dexter2206@gmail.com>", "Łukasz Pawela <lukasz.pawela@gmail.com>"]
version = "0.4.4"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"

[compat]
Graphs = "1.9"
MetaGraphs = "0.7"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
