name: Release package
on: workflow_dispatch


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
          output-file: 'changelog.md'
          release-count: '1000'
          version-file: './Project.toml'
          version-path: 'version'
      - name: Extract last commit's ref
        id: git
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Trigger registrator
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            @JuliaRegistrator register
          sha: ${{ steps.git.outputs.sha_short }}
